### PR TITLE
Added article view

### PR DESCRIPTION
**Pull request by 21atran**
hi :)

### CODE REVIEW

**Comment by MandarinPine18** [comment]
Okay, so it's pretty good - I'm just going to make a few alignment and color tweaks.

**Comment by MandarinPine18** [comment]
There also might be an easier way to do some of this stuff. You'll see what I mean if you check out my coming commits.

**Comment by MandarinPine18** [comment]
I managed to fix up the top bar issue. I know horizontal stacks can be a little funky, so I switched it over to an equivalent grid layout. You should check that out.

Also, we set the theme colors a while back as a dynamic resource, so instead of using

> Color="ForestGreen"

we can use

> Color="{DynamicResource Primary}"

which gets you the actual theme color.

**Comment by MandarinPine18** [comment]
I'm sorry, but this made me chuckle a little. Using an empty label as a makeshift spacer is definitely creative, but instead of

```xaml
<Label 
    Text=" "
    VerticalOptions="Center" 
    HorizontalOptions="Fill"
    FontAttributes="Bold"
    FontSize="2"
    BackgroundColor="PaleGreen"/>
```

we can accomplish something like that with something a little simpler,

```xaml
<Rectangle
    HeightRequest="2"
    BackgroundColor="{DynamicResource Secondary}"/>
```

The perseverance is admirable, though.

**Comment by MandarinPine18** [comment]
Okay, it looks good enough to me. Let me know what you think as another comment here, @21atran. I'm going to try importing a font for the top bar, but that's the only thing left that I want to try.

**Comment by 21atran** [comment]
Looks great!

**Review by MandarinPine18 — APPROVED** [review]
Alrighty, after a few quick modifications and adding the font, it looks like it's in tip-top shape. I left in the wonky spacers for the image placeholder because we'll have to swap them out for an image tag in integration anyways. I'm pulling it into release.

**Pull request merged**
